//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode22Day15.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode22Day15.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor at x=545406, y=2945484: closest beacon is at x=772918, y=2626448
        ///Sensor at x=80179, y=3385522: closest beacon is at x=772918, y=2626448
        ///Sensor at x=2381966, y=3154542: closest beacon is at x=2475123, y=3089709
        ///Sensor at x=2607868, y=1728571: closest beacon is at x=2715626, y=2000000
        ///Sensor at x=746476, y=2796469: closest beacon is at x=772918, y=2626448
        ///Sensor at x=911114, y=2487289: closest beacon is at x=772918, y=2626448
        ///Sensor at x=2806673, y=3051666: closest beacon is at x=2475123, y=30897 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor at x=2, y=18: closest beacon is at x=-2, y=15
        ///Sensor at x=9, y=16: closest beacon is at x=10, y=16
        ///Sensor at x=13, y=2: closest beacon is at x=15, y=3
        ///Sensor at x=12, y=14: closest beacon is at x=10, y=16
        ///Sensor at x=10, y=20: closest beacon is at x=10, y=16
        ///Sensor at x=14, y=17: closest beacon is at x=10, y=16
        ///Sensor at x=8, y=7: closest beacon is at x=2, y=10
        ///Sensor at x=2, y=0: closest beacon is at x=2, y=10
        ///Sensor at x=0, y=11: closest beacon is at x=2, y=10
        ///Sensor at x=20, y=14: closest [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputTest {
            get {
                return ResourceManager.GetString("InputTest", resourceCulture);
            }
        }
    }
}
