//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode22Day25.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode22Day25.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2=1121==100=22
        ///22-0==122-1-
        ///10-10-2=012=2=1==1
        ///1--000-=12-
        ///1=2=
        ///1==--2--22-=
        ///11-=20==-1-211=1-21
        ///1=2-0200=-012=
        ///10=2--211
        ///2=
        ///1-=
        ///1==2
        ///21==-=202=2
        ///2==1=0==12=11=
        ///1=-00=201=2-==
        ///1-0=0=2=-2-0=-1=
        ///1=2==
        ///2=1202211-
        ///2-=11=
        ///122=01-
        ///20=000=12-210-00-0-
        ///1020=-212002
        ///110==21100=-
        ///1-=1=11-2-1=
        ///22-=00011=-01-1-
        ///20-2=22
        ///1=02=01002---=0
        ///12-==-2==020
        ///1-22
        ///10
        ///2
        ///20121
        ///1001--102=-
        ///1=20==011=-=
        ///2100=--1112
        ///102=
        ///1--=2-20100---1=2-
        ///100=02-2=00010
        ///2=212-01-1-200--=-
        ///1001121
        ///1222
        ///1==-1-
        ///1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1=-0-2
        ///12111
        ///2=0=
        ///21
        ///2=01
        ///111
        ///20012
        ///112
        ///1=-1=
        ///1-12
        ///12
        ///1=
        ///122.
        /// </summary>
        internal static string InputTest {
            get {
                return ResourceManager.GetString("InputTest", resourceCulture);
            }
        }
    }
}
