//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode22Day01.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode22Day01.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9609
        ///7601
        ///7142
        ///5278
        ///9374
        ///6815
        ///1050
        ///6329
        ///8016
        ///
        ///12477
        ///28601
        ///
        ///1056
        ///5037
        ///1660
        ///3786
        ///2611
        ///6689
        ///3159
        ///2973
        ///5286
        ///2401
        ///6231
        ///7460
        ///
        ///3689
        ///3909
        ///9254
        ///5704
        ///10307
        ///10173
        ///9336
        ///4586
        ///
        ///5476
        ///16022
        ///9109
        ///11504
        ///6746
        ///
        ///1006
        ///1685
        ///2688
        ///4776
        ///6234
        ///5807
        ///4943
        ///4944
        ///4982
        ///1731
        ///3196
        ///5573
        ///5269
        ///1266
        ///
        ///12097
        ///15573
        ///1113
        ///8920
        ///14145
        ///
        ///4723
        ///2428
        ///3864
        ///4657
        ///5046
        ///5135
        ///5104
        ///1867
        ///5130
        ///1751
        ///6029
        ///4551
        ///1924
        ///4998
        ///4255
        ///
        ///2706
        ///5595
        ///10508
        ///3676
        ///11580
        ///6061
        ///7902
        ///
        ///2523
        ///11236
        ///1915
        ///15 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
    }
}
