//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode22Day20.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode22Day20.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -6287
        ///6707
        ///6969
        ///2869
        ///4724
        ///-4370
        ///587
        ///-1247
        ///7741
        ///4838
        ///6192
        ///2045
        ///5948
        ///-2006
        ///-6210
        ///-8096
        ///-7765
        ///4391
        ///-8005
        ///-5786
        ///-3773
        ///2122
        ///3081
        ///-5430
        ///8527
        ///7219
        ///6974
        ///-637
        ///-1005
        ///3521
        ///8089
        ///9898
        ///2212
        ///-3129
        ///-4205
        ///-9778
        ///-3048
        ///-7358
        ///-981
        ///-3167
        ///-9093
        ///-8453
        ///1604
        ///4036
        ///-1201
        ///-996
        ///8026
        ///-3139
        ///3729
        ///-7911
        ///-9299
        ///-5416
        ///-4008
        ///4564
        ///3496
        ///-8191
        ///75
        ///7499
        ///-5445
        ///8535
        ///-9058
        ///7848
        ///-3293
        ///-7887
        ///1209
        ///-4421
        ///-4968
        ///-5271
        ///-8239
        ///7648
        ///-7478
        ///-6769
        ///1961
        ///-206
        ///-2179
        ///-9216
        ///8078
        ///9530
        ///3628
        ///65 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///2
        ///-3
        ///3
        ///-2
        ///0
        ///4.
        /// </summary>
        internal static string InputTest {
            get {
                return ResourceManager.GetString("InputTest", resourceCulture);
            }
        }
    }
}
