//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode22Day07.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode22Day07.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ cd /
        ///$ ls
        ///115454 dwdllt
        ///dir jmdf
        ///dir jrgzmphz
        ///dir pdzrzbtf
        ///177917 pvlvsfjw.qvw
        ///dir qlpvwf
        ///30151 qvrwp.vsv
        ///73443 wzbtj
        ///$ cd jmdf
        ///$ ls
        ///228633 gdbv.qjv
        ///252639 pphmpmms.rrn
        ///dir rgrcs
        ///$ cd rgrcs
        ///$ ls
        ///34044 cqldc.nmr
        ///dir drg
        ///dir gcfth
        ///266939 phcfhh
        ///$ cd drg
        ///$ ls
        ///200446 cjclf
        ///94067 phcfhh
        ///121940 twsswl.nzb
        ///235672 vmzlzqgc.ppj
        ///179660 zqbczf
        ///$ cd ..
        ///$ cd gcfth
        ///$ ls
        ///49306 bsqqhqv.thv
        ///dir zsmhsbp
        ///$ cd zsmhsbp
        ///$ ls
        ///152706 vmcf.rsw
        ///$ cd ..
        ///$ cd ..
        ///$ cd ..
        ///$ cd ..
        ///$ cd jrgzmphz
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
    }
}
