//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode22Day21.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode22Day21.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mlgm: dssb * wjbz
        ///ptqp: 2
        ///ncnt: 5
        ///hzfs: gbsq * fbbz
        ///htwj: qcnb * rlmh
        ///qlzl: 2
        ///hrfp: 5
        ///hbsl: ddqr * ffgz
        ///vcsd: 2
        ///pght: 17
        ///mvwb: 10
        ///mmpr: 3
        ///mhhm: rcsd + cmbv
        ///ldjn: 4
        ///rjcv: qqbm / qlgp
        ///hbcq: hmtb * mzsr
        ///ctgj: 7
        ///qzjg: mwdq * fdfd
        ///bpgs: 3
        ///qfpf: 2
        ///ztmc: 3
        ///thpt: lsrn / wsqj
        ///zwmj: tdsz * drch
        ///btgl: 3
        ///jnpp: hdpn * hrfp
        ///lbbz: cfww * prtb
        ///sbqc: rmrr * ppms
        ///fprb: 3
        ///hvmh: 8
        ///sznb: 9
        ///nstl: fmcd * zwml
        ///gwtg: 3
        ///rmtm: 14
        ///dprf: nccf - jnwn
        ///gtjs: gfgq + shbd
        ///mnjj: 2
        ///dtdm: 6
        ///wchv: 4
        ///tqjb: t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to root: pppw + sjmn
        ///dbpl: 5
        ///cczh: sllz + lgvd
        ///zczc: 2
        ///ptdq: humn - dvpt
        ///dvpt: 3
        ///lfqf: 4
        ///humn: 5
        ///ljgn: 2
        ///sjmn: drzm * dbpl
        ///sllz: 4
        ///pppw: cczh / lfqf
        ///lgvd: ljgn * ptdq
        ///drzm: hmdt - zczc
        ///hmdt: 32.
        /// </summary>
        internal static string InputTest {
            get {
                return ResourceManager.GetString("InputTest", resourceCulture);
            }
        }
    }
}
