//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode22Day18.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode22Day18.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,8,9
        ///5,11,3
        ///11,7,16
        ///13,14,4
        ///11,3,10
        ///15,15,13
        ///13,5,9
        ///9,14,3
        ///2,11,11
        ///6,13,15
        ///3,12,11
        ///8,12,17
        ///2,9,8
        ///12,8,15
        ///5,11,6
        ///8,2,12
        ///9,5,2
        ///12,13,15
        ///10,15,7
        ///14,12,3
        ///10,2,6
        ///14,5,15
        ///16,11,9
        ///13,15,14
        ///3,4,12
        ///3,8,6
        ///8,8,1
        ///12,3,8
        ///12,14,5
        ///3,11,12
        ///16,14,9
        ///16,5,14
        ///7,6,5
        ///3,6,5
        ///16,12,9
        ///4,13,12
        ///7,16,9
        ///1,11,10
        ///11,4,14
        ///5,16,7
        ///11,15,7
        ///9,15,14
        ///10,16,7
        ///13,3,14
        ///10,1,8
        ///17,9,6
        ///6,3,10
        ///3,5,9
        ///6,12,3
        ///12,6,16
        ///7,12,4
        ///13,12,16
        ///14,3,9
        ///11,8,3
        ///17,8,11
        ///7,13,2
        ///3,6,8
        ///14,15,10
        ///8,6,3
        ///6,2,9
        ///10,17,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2,2,2
        ///1,2,2
        ///3,2,2
        ///2,1,2
        ///2,3,2
        ///2,2,1
        ///2,2,3
        ///2,2,4
        ///2,2,6
        ///1,2,5
        ///3,2,5
        ///2,1,5
        ///2,3,5.
        /// </summary>
        internal static string InputTest {
            get {
                return ResourceManager.GetString("InputTest", resourceCulture);
            }
        }
    }
}
