//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode22Day22.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode22Day22.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                                   ......#...........#..............#.......#.#..............#...................#...#.................
        ///                                                  ..........#...........#.......#..........#...#.............#..#..#.#....#......................#....
        ///                                                  ..........#..................#.................#.#............##.......#..........#......#.......#.#
        ///                                                  .....# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 39L35R25L7R47L28R8L33R20R40R33R11L32L6L14R9R13R49L32R24R40R49L8R7L28L7L34R12R29L12R25R26L7R33L18R25L32L29R13L8R4R42L24L23L8L50L9L46R10L47L17L16R44L4L18L43R26L16R3R25L33L50R42L13R16L32R46R19R50R40R19R8L4R1L39L26R14L27R22R48L21R16R14R44L32L1L6R26L3L24R11L15R43R34L2L2L15R16R12R29R40L32L36L20L22L43R50L38R44L41L22L32L13R42L10R18L48R45L24R15L22L20R5R37R30L22R13L7R31L8L38R3R13L14R28L28R17R27L40R5L24R20L11R27R4R29R25R11L21L21R39R44R15L46L23L6L40R31L40R15R48R33R22R6L50R18L16R22R14L50R39L16L32R49R3R43L8R13R30L28R13R3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input2 {
            get {
                return ResourceManager.GetString("Input2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         ...#
        ///        .#..
        ///        #...
        ///        ....
        ///...#.......#
        ///........#...
        ///..#....#....
        ///..........#.
        ///        ...#....
        ///        .....#..
        ///        .#......
        ///        ......#..
        /// </summary>
        internal static string InputTest1 {
            get {
                return ResourceManager.GetString("InputTest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10R5L5R10L4R5L5.
        /// </summary>
        internal static string InputTest2 {
            get {
                return ResourceManager.GetString("InputTest2", resourceCulture);
            }
        }
    }
}
