//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode22Day24.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode22Day24.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.########################################################################################################################
        ///#.&lt;v&gt;&gt;&lt;&lt;&lt;^v&lt;&gt;^&lt;^vv.^&lt;^^^&lt;^v&gt;&lt;&gt;vv&lt;v^.^v&gt;v.^&gt;&lt;v..&lt;&gt;&lt;..vv&gt;&lt;v.&lt;.v&lt;&lt;^.&gt;&gt;&gt;&gt;&gt;&gt;^&lt;^&gt;^&gt;vv&lt;^&gt;&gt;^v^.&lt;.&lt;&lt;&gt;^&lt;&lt;&gt;^&gt;&gt;^&gt;.&gt;&lt;&gt;.^&gt;.v^&lt;&lt;&gt;&lt;&lt;^vvv&lt;#
        ///#&gt;.&lt;v&gt;v&lt;&gt;v&gt;vv^.&lt;&gt;^^v.&gt;&lt;&lt;^&gt;^v^&lt;&gt;v^&gt;&gt;&gt;&gt;&lt;&lt;^&lt;^vv&gt;v&gt;&gt;&lt;^&gt;v.^v&lt;&lt;^v&lt;.&lt;&gt;v&gt;&gt;^&gt;&lt;&gt;&gt;^&gt;^&lt;&gt;v&lt;&gt;&lt;&lt;&gt;.v.^&lt;.&lt;&lt;&gt;vvv&lt;^v.&lt;&gt;v&gt;^^vv^^^&lt;&gt;^^&lt;&lt;&lt;^&lt;v&gt;&gt;#
        ///#&gt;&lt;.&lt;&lt;vvv&lt;&gt;.vvv&lt;&gt;&lt;^&lt;&gt;v&lt;.v&gt;v.&lt;&gt;^&gt;^v&gt;^&lt;&lt;&gt;&lt;vv^&lt;v&gt;&gt;&lt;vv&lt;&lt;&gt;&lt;^^^v^&gt;^..&lt;&lt;^&lt;.&gt;&lt;v&lt;v&gt;^^v.&lt;&lt;vv&lt;v^^&gt;vv&gt;&lt;&lt;&gt;^v&gt;&lt;&gt;&gt;&lt;&gt;^&lt;^^^^v^&lt;&gt;&gt;&lt;.vvvv.&lt;&....
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.######
        ///#&gt;&gt;.&lt;^&lt;#
        ///#.&lt;..&lt;&lt;#
        ///#&gt;v.&gt;&lt;&gt;#
        ///#&lt;^v^^&gt;#
        ///######.#.
        /// </summary>
        internal static string InputTest {
            get {
                return ResourceManager.GetString("InputTest", resourceCulture);
            }
        }
    }
}
