//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode22Day14.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode22Day14.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 476,63 -&gt; 481,63
        ///478,93 -&gt; 478,87 -&gt; 478,93 -&gt; 480,93 -&gt; 480,90 -&gt; 480,93 -&gt; 482,93 -&gt; 482,83 -&gt; 482,93 -&gt; 484,93 -&gt; 484,88 -&gt; 484,93 -&gt; 486,93 -&gt; 486,83 -&gt; 486,93 -&gt; 488,93 -&gt; 488,90 -&gt; 488,93 -&gt; 490,93 -&gt; 490,87 -&gt; 490,93
        ///489,96 -&gt; 489,98 -&gt; 482,98 -&gt; 482,101 -&gt; 496,101 -&gt; 496,98 -&gt; 494,98 -&gt; 494,96
        ///489,96 -&gt; 489,98 -&gt; 482,98 -&gt; 482,101 -&gt; 496,101 -&gt; 496,98 -&gt; 494,98 -&gt; 494,96
        ///478,93 -&gt; 478,87 -&gt; 478,93 -&gt; 480,93 -&gt; 480,90 -&gt; 480,93 -&gt; 482,93 -&gt; 482,83 -&gt; 482,93 -&gt; 484,93 -&gt; 484,88 -&gt; 484,93 -&gt; 486,93 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 498,4 -&gt; 498,6 -&gt; 496,6
        ///503,4 -&gt; 502,4 -&gt; 502,9 -&gt; 494,9.
        /// </summary>
        internal static string InputTest {
            get {
                return ResourceManager.GetString("InputTest", resourceCulture);
            }
        }
    }
}
